version: "3.4"

services:
  db1_v5_1:
    container_name: db1_v5_1
    environment:
      - MYSQL_ROOT_PASSWORD=pass123
      - MYSQL_DATABASE=enterprise_v5_1
      - MYSQL_USER=client1
      - MYSQL_PASSWORD=pass123
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - db1_v5_1_data:/var/lib/mysql
    restart: unless-stopped
    tty: true

  db2_v5_1:
    container_name: db2_v5_1
    environment:
      - MYSQL_ROOT_PASSWORD=pass123
      - MYSQL_DATABASE=enterprise_v5_1
      - MYSQL_USER=client2
      - MYSQL_PASSWORD=pass123
    image: mysql:5.7
    ports:
      - 3307:3306
    volumes:
      - db2_v5_1_data:/var/lib/mysql
    restart: unless-stopped
    tty: true

  db3_v5_2:
    container_name: db3_v5_2
    environment:
      - MYSQL_ROOT_PASSWORD=pass123
      - MYSQL_DATABASE=enterprise_v5_2
      - MYSQL_USER=client3
      - MYSQL_PASSWORD=pass123
    image: mysql:5.7
    ports:
      - 3308:3306
    volumes:
      - db3_v5_2_data:/var/lib/mysql
    restart: unless-stopped
    tty: true

  db4_v5_2:
    container_name: db4_v5_2
    environment:
      - MYSQL_ROOT_PASSWORD=pass123
      - MYSQL_DATABASE=enterprise_v5_2
      - MYSQL_USER=client4
      - MYSQL_PASSWORD=pass123
    image: mysql:5.7
    ports:
      - 3309:3306
    volumes:
      - db4_v5_2_data:/var/lib/mysql
    restart: unless-stopped
    tty: true

volumes:
  db1_v5_1_data:
  db2_v5_1_data:
  db3_v5_2_data:
  db4_v5_2_data:
